# Generated by Django 6.0.4 on 2026-04-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoSoCongTy',
            fields=[
                ('cong_ty', models.OneToOneField(db_column='cong_ty_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ho_so_cong_ty', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ten_cong_ty', models.CharField(max_length=255)),
                ('linh_vuc', models.CharField(blank=True, max_length=255, null=True)),
                ('lich_su', models.TextField(blank=True, null=True)),
                ('lien_he', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HO_SO_CONG_TY',
            },
        ),
        migrations.CreateModel(
            name='HoSoUngVien',
            fields=[
                ('ung_vien', models.OneToOneField(db_column='ung_vien_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ho_so_ung_vien', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ho_ten', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('ky_nang', models.TextField(blank=True, null=True)),
                ('vi_tri_mong_muon', models.CharField(blank=True, max_length=255, null=True)),
                ('thoi_gian_ranh', models.CharField(blank=True, max_length=255, null=True)),
                ('luong_mong_muon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'HO_SO_UNG_VIEN',
            },
        ),
    ]
