# Generated by Django 5.2.13 on 2026-04-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_candidate_viewing_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hosocongty",
            old_name="lien_he",
            new_name="tru_so_chinh",
        ),
        migrations.AddField(
            model_name="hosocongty",
            name="cac_du_an",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hosocongty",
            name="gioi_thieu",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hosocongty",
            name="nam_thanh_lap",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hosocongty",
            name="so_luong_nhan_vien",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hosocongty",
            name="thong_tin_lien_he",
            field=models.TextField(blank=True, null=True),
        ),
    ]
