# Generated by Django 6.0.4 on 2026-04-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_hosoungvien_chung_chi_hosoungvien_du_an_and_more"),
        ("profiles", "0003_rename_lien_he_hosocongty_tru_so_chinh_and_more"),
    ]

    operations = []
