# Generated by Django 6.0.4 on 2026-04-08 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('danh_gia_id', models.AutoField(primary_key=True, serialize=False)),
                ('diem_so', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nhan_xet', models.TextField(blank=True, null=True)),
                ('tao_luc', models.DateTimeField(auto_now_add=True)),
                ('nguoi_danh_gia', models.ForeignKey(db_column='nguoi_danh_gia_id', on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_da_viet', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan_danh_gia', models.ForeignKey(db_column='nguoi_nhan_danh_gia_id', on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_da_nhan', to=settings.AUTH_USER_MODEL)),
                ('ung_tuyen', models.ForeignKey(db_column='ung_tuyen_id', on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='applications.ungtuyen')),
            ],
            options={
                'db_table': 'DANH_GIA',
            },
        ),
    ]
