# Generated by Django 6.0.4 on 2026-04-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuyenDung',
            fields=[
                ('tin_id', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('bat_dau_lam', models.DateTimeField()),
                ('ket_thuc_lam', models.DateTimeField()),
                ('luong_theo_gio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_diem_lam_viec', models.CharField(max_length=255)),
                ('trang_thai', models.CharField(choices=[('dang_mo', 'Dang mo'), ('da_dong', 'Da dong')], default='dang_mo', max_length=20)),
                ('tao_luc', models.DateTimeField(auto_now_add=True)),
                ('cong_ty', models.ForeignKey(db_column='cong_ty_id', on_delete=django.db.models.deletion.CASCADE, related_name='tin_tuyen_dung', to='profiles.hosocongty')),
            ],
            options={
                'db_table': 'TIN_TUYEN_DUNG',
            },
        ),
    ]
