# Generated by Django 6.0.4 on 2026-04-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UngTuyen',
            fields=[
                ('ung_tuyen_id', models.AutoField(primary_key=True, serialize=False)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Cho duyet'), ('chap_nhan', 'Chap nhan'), ('tu_choi', 'Tu choi'), ('hoan_thanh', 'Hoan thanh')], default='cho_duyet', max_length=20)),
                ('thoi_gian_ung_tuyen', models.DateTimeField(auto_now_add=True)),
                ('tin', models.ForeignKey(db_column='tin_id', on_delete=django.db.models.deletion.CASCADE, related_name='ung_tuyen', to='jobs.tintuyendung')),
                ('ung_vien', models.ForeignKey(db_column='ung_vien_id', on_delete=django.db.models.deletion.CASCADE, related_name='ung_tuyen', to='profiles.hosoungvien')),
            ],
            options={
                'db_table': 'UNG_TUYEN',
            },
        ),
    ]
