# Generated by Django 6.0.4 on 2026-04-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('tin_nhan_id', models.AutoField(primary_key=True, serialize=False)),
                ('noi_dung_tin_nhan', models.TextField()),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(db_column='nguoi_gui_id', on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_da_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(db_column='nguoi_nhan_id', on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_da_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CHAT',
            },
        ),
    ]
