# Generated by Django 6.0.4 on 2026-04-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('thong_bao_id', models.AutoField(primary_key=True, serialize=False)),
                ('loai_thong_bao', models.CharField(choices=[('tin_moi', 'Tin moi'), ('match_thanh_cong', 'Match thanh cong'), ('tin_nhan_moi', 'Tin nhan moi')], max_length=30)),
                ('noi_dung', models.TextField()),
                ('da_doc', models.BooleanField(default=False)),
                ('tao_luc', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'THONG_BAO',
            },
        ),
    ]
